# Generated by Django 5.0.6 on 2024-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('em', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=30)),
                ('repassw', models.CharField(max_length=30)),
            ],
        ),
    ]
